In [1]:
import pandas as pd
import numpy as np

### Creating a One dimentional Array

In [2]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

### Checking the data type for an array

In [3]:
type(arr1)

numpy.ndarray

### Creating a Two dimensional Array

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
type(arr2)

numpy.ndarray

### Creating a Three dimensional Array

In [6]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
type(arr3)

numpy.ndarray

### Get the Number of Rows and Columns of an array

#### Shape of arr1

In [8]:
arr1.shape

(3,)

#### Shape of arr2

In [9]:
arr2.shape

(2, 3)

#### Shape of arr3

In [10]:
arr3.shape

(2, 3, 3)

### Get the dimensions of an array

#### Dimensions of arr1

In [11]:
arr1.ndim

1

#### Dimensions of arr2

In [12]:
arr2.ndim

2

#### Dimensions of arr3

In [13]:
arr3.ndim

3

### Get the data types of arrays

### Data type of arr1

In [14]:
arr1.dtype

dtype('int64')

### Data type of arr2

In [15]:
arr2.dtype

dtype('int64')

### Data type of arr3

In [16]:
arr3.dtype

dtype('int64')

### Data type of arr4

In [17]:
arr4 = np.array([[[1,2,3],[4.3,3.2,7.6],['a','b','c']],[['e','f','g'],[1,2,3],[3.2,2.1,1.6]]])
arr4.dtype,arr4.ndim

(dtype('<U32'), 3)

### Get the size of an array
#### It will show how many elements are in the array

In [18]:
arr1.size

3

In [19]:
arr2.size

6

In [20]:
arr3.size

18

In [21]:
arr4.size

18

### Creating a dataframe from a numpy array

In [22]:
df = pd.DataFrame(arr1)
df

0
0  1
1  2
2  3

In [23]:
df1 = pd.DataFrame(arr2)
df1

0  1  2
0  1  2  3
1  4  5  6

In [24]:
df3 = pd.DataFrame(arr3)
df3

ValueError: Must pass 2-d input. shape=(2, 3, 3)

### Create a dataframe includes only 1

In [ ]:
df2 = np.ones((3,3))
df2

### Create a dataframe includes only 0

In [ ]:
df3 = np.zeros((3,3))
df3

### Create a dataframe from range and random function

In [ ]:
range_df = np.arange(0,10,1)
range_df

In [ ]:
random_df = np.random.randint(5,20,size=(2,4))
random_df

In [ ]:
random_df.size

In [ ]:
random_df.shape

In [ ]:
random_df.ndim

In [ ]:
random_df1 = np.random.random((2,3))
random_df1

In [ ]:
random_df2 = np.random.rand(3,3)
random_df2

### Creating a random values in a dataframe using Random seed

In [ ]:
np.random.seed(seed=0)
df_random_seed = pd.DataFrame(np.random.rand(2,3))
df_random_seed

### Get a unqiue values from a dataframe

In [ ]:
random_df

In [ ]:
np.uniaque(random_df)

### Numpy Arithmetic Operators

In [ ]:
a1 = np.random.randint(1,10,size=(3,3))
a1

In [ ]:
a2 = np.random.randint(11,19,size=(3,4))
a2

In [ ]:
a3 = np.random.randint(11,19,size=(3,3))
a3

In [ ]:
a1*a3

In [ ]:
a1-a3

In [ ]:
a1**a3

In [ ]:
a1+a3

In [ ]:
a1/a3

In [ ]:
np.square(a3)

### Aggregate Function

In [ ]:
lst = [1,2,3,4,5]

In [ ]:
%%timeit
sum(lst)

In [ ]:
%%timeit
np.sum(lst)

### Reshape the numpy array

In [ ]:
nparr1 = np.random.randint(11,100,size=(2,3))
nparr1

In [ ]:
nparr2 = np.random.rand(4,3)
nparr2

In [ ]:
nparr1*nparr2

In [ ]:
nparr1.shape

In [ ]:
nparr2.shape

In [ ]:
nparr1.reshape(2,3)

In [ ]:
nparr1.shape

In [ ]:
nparr1*nparr2

### Transpose the numpy array

In [25]:
array = np.random.rand(2,3)

In [26]:
array

array([[0.94429012, 0.08923812, 0.70857024],
       [0.47552012, 0.26378195, 0.54076735]])

In [27]:
array.T

array([[0.94429012, 0.47552012],
       [0.08923812, 0.26378195],
       [0.70857024, 0.54076735]])

In [28]:
array.T.shape

(3, 2)

### Element wise multiplication

In [29]:
a1 = np.random.randint(1,30,size=(3,3))
a2 = np.random.randint(31,60,size=(3,3))

In [30]:
a1

array([[28, 10, 23],
       [16, 10,  1],
       [19,  4, 13]])

In [31]:
a2

array([[37, 37, 48],
       [31, 44, 52],
       [49, 31, 52]])

In [32]:
a1*a2

array([[1036,  370, 1104],
       [ 496,  440,   52],
       [ 931,  124,  676]])

### Dot product

In [33]:
np.dot(a1,a2)

array([[2473, 2189, 3060],
       [ 951, 1063, 1340],
       [1464, 1282, 1796]])

### Comparison Operator

In [39]:
array1 = np.random.randint(3,6,size=(2,3))
array1

array([[5, 4, 3],
       [4, 4, 4]])

In [38]:
array2 = np.random.randint(2,9,size=(2,3))
array2

array([[2, 6, 6],
       [2, 8, 3]])

In [40]:
array1>=array2

array([[ True, False, False],
       [ True, False,  True]])

### Sorting an arrays

In [41]:
array1

array([[5, 4, 3],
       [4, 4, 4]])

In [42]:
np.sort(array1)

array([[3, 4, 5],
       [4, 4, 4]])

In [43]:
np.argsort(array1)

array([[2, 1, 0],
       [0, 1, 2]])

In [44]:
np.argmin(array1)

2